### ISSUE TITLE
iconfont问题

### ISSUE THREAD

**Issue by ChiaJune** [SidKwok/react-webpack-boilerplate#31]
我在文件中引入`font-awesome`（已经安装了）
我是这样引入的：`import 'font-awesome/css/font-awesome.css'`
结果打包出来是这样的：
``` css
@font-face {
    font-family:FontAwesome;
    src:url([object Object]);
    src:url([object Object]?#iefix&v=4.7.0) format("embedded-opentype"), url([object Object]) format("woff2"), url([object Object]) format("woff"), url([object Object]) format("truetype"), url([object Object]#fontawesomeregular) format("svg");
    font-weight:400;
    font-style:normal
}
```
其实，开发环境也是这样的，不知道是什么原因
